export const ADD_INFOS="ADD_INFOS";
export const ADD_ALL_DATAS="ADD_ALL_DATAS";
export const ADD_ALL_APP_DATAS="ADD_ALL_APP_DATAS";
export const GET_FILTER_DATA="GET_FILTER_DATA";
export const GET_FILTER_APP_DATA="GET_FILTER_APP_DATA";
export const GET_CHOSEN_INFO="GET_CHOSEN_INFO";
